In [15]:
# ndarray数组对象的维度操作
# 视图变维(数据共享) reshape()与ravel()
import numpy as np
a = np.arange(1, 9)
print(a, a.shape)
# 视图变维：变为2行4列的二维数组
b = a.reshape(2, 4)
print(b, b.shape)
# 视图变维：变为2页2行4列的三维数组
c = b.reshape(2, 2, 2)
print(c, c.shape)
# 视图变维：变为一维数组
d = c.ravel()
print(d)
print("----------------------------")
# 复制变维-数据独立  flatten()和copy()
# 变维一维数组
e = c.flatten()
print(e, e.shape)
# flatten，数据独立，修改元数据，不会影响新数据
c[0][0] = 100
print(e, e.shape)
# copy当前数组
f = c.copy()
print(f, f.shape)

# 就地变维 
e.shape = (-1, 8)
print(e, e.shape)


[1 2 3 4 5 6 7 8] (8,)
[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
[1 2 3 4 5 6 7 8]
----------------------------
[1 2 3 4 5 6 7 8] (8,)
[1 2 3 4 5 6 7 8] (8,)
[[[100 100]
  [  3   4]]

 [[  5   6]
  [  7   8]]] (2, 2, 2)
[[1 2 3 4 5 6 7 8]] (1, 8)
