In [13]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
print(ary, type(ary))
print(ary + 10)
print(ary * 2)
print(ary + ary)
b = [True, False]
print(b)
a = [b]
print(a)

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[11 12 13 14 15 16]
[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]
[True, False]
[[True, False]]


In [22]:
import numpy as np
a = np.arange(0, 5, 1)
# 起始值0，终止值5，步长1
print(a)
a1 = np.arange(0, 10, 2)
# 起始值0，终止值10，步长2
print(a1)

[0 1 2 3 4]
[0 2 4 6 8]


In [26]:
import numpy as np
a2 = np.zeros(10)
print(a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a, a.shape)

b = np.arange(1, 10)
print(b)

# 10个0
c = np.zeros(10, dtype='float32')
print(c)

# 3x3个1
d = np.ones((3, 3), dtype='int32')
print(d)

# 创建一个结构像d的数组，元素都为0
e = np.zeros_like(d)
print(e)

f = np.ones_like(e)
print(f)
print(f * 3)
print(np.ones(5) / 5)

[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[0.2 0.2 0.2 0.2 0.2]


In [53]:
import numpy as np
# 数组的维度
ary = np.arange(1, 7)
print(ary, ary.shape)

# 修改维度
ary.shape = (2, 3)
print(ary, ary.shape)

# 修改元素类型
ary = ary.astype('float64')
print(ary, ary.dtype)

# 数组长度
print('size:',ary.size, 'len:',len(ary))

# 数组索引
a = np.arange(1, 19)
print(a)
# 3页、2行、3列
a.shape = (3, 2, 3)
print(a)
print(a[0])
print(a[0][0])
print(a[0][0][0])
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            print(a[i, j, k])

[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[1. 2. 3.]
 [4. 5. 6.]] float64
size: 6 len: 2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
