In [29]:
import numpy as np
# 多维数组切片
a = np.arange(1,28)
a.resize(3, 3, 3)
print(a)
print("----------------")
print(a[:2, :2])
print(a[::2, ::2])
# # 切出1页
# print(a[1, :, :])
# print("----------------")
# # 切出所有页的1行
# print(a[:, 1, :])
# print("----------------")
# # 切出所有页的1列
# print(a[:, :, 1])
# print("----------------")
# # 切出0页的1行1列
# print(a[0, 1, 1])
# print(a[0, :, 0])

# ndarray数组的掩码操作
a = np.arange(1, 10)
mask = [True, False, True, False, True, False, True, False, True]
print(a[mask])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
----------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[19 20 21]
  [25 26 27]]]
[1 3 5 7 9]
